parameters:
  environment: "" 

jobs:
  - deployment: 
    environment: ${{ parameters.environment }}
    displayName: Validate ${{ parameters.environment }} Approval
    strategy:
      runOnce:
        deploy:
          steps:
            - download: none  # skip the default Download Artifacts part of the task
            - bash: echo "Deploying ${{ parameters.environment }} environment"
              displayName: Check for Approval
