# Simple pipeline that just bundles all the Infrastructure
# as Code (IaC) files together as the build artifact
#

pool:
  name: Hosted Ubuntu 1604
steps:
- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.StagingDirectory)'
  inputs:
    TargetFolder: '$(Build.StagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'

