name: api-deploy

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - api/*
      - pipelines/api-build.yml
      - pipelines/api-deploy.yml
      - pipelines/templates/api-build.yml
      - pipelines/templates/api-deploy-environment.yml
      - pipelines/templates/deployment-gate.yml

pr: none

pool:
  vmImage: "ubuntu-latest"

variables:
  - group: prodoh-urlist-common

stages:
  - stage: BuildAndValidate
    displayName: Build & Validate
    jobs:
      - template: templates/api-build.yml

  - stage: Development
    displayName: Development
    dependsOn: BuildAndValidate
    variables:
      - group: prodoh-urlist-dev
    jobs:
      - template: templates/api-deploy-environment.yml
        parameters:
          subscription: $(azureSubscription)
          businessUnit: $(businessUnit)
          appName: $(appName)
          environment: dev
          regions:
            - westus2

  - stage: Staging
    displayName: Staging
    dependsOn: Development
    variables:
      - group: prodoh-urlist-staging
    jobs:
      - template: templates/api-deploy-environment.yml
        parameters:
          subscription: $(azureSubscription)
          businessUnit: $(businessUnit)
          appName: $(appName)
          environment: staging
          regions:
            - westus2
            - eastus

  - stage: Production
    displayName: Production
    dependsOn: Staging
    variables:
      - group: prodoh-urlist-prod
    jobs:
      - template: templates/api-deploy-environment.yml
        parameters:
          subscription: $(azureSubscription)
          businessUnit: $(businessUnit)
          appName: $(appName)
          environment: prod
          regions:
            - westus2
            - eastus
            - centralus
