name: api-build

pr:
  autoCancel: true
  branches:
    include:
      - master
  paths:
    include:
      - api/*
      - pipelines/api-build.yml
      - pipelines/templates/api-build.yml

pool:
  vmImage: "ubuntu-latest"

variables:
  - group: prodoh-urlist-common

stages:
  - stage: BuildAndValidate
    displayName: Build & Validate
    jobs:
      - template: templates/api-build.yml
