name: $(Date:yyyyMMdd)$(Rev:.r) # build numbering format

trigger: none

pool:
  vmImage: "ubuntu-latest"

variables:
  - group: prodoh-urlist-common

stages:
  - stage: BuildAndValidate
    displayName: Build & Validate
    jobs:
      - template: templates/api-build.yml
