trigger:
  branches:
    include:
      - master
  paths:
    include:
      - api/*
  
  pr:
    autoCancel: true   
    branches:
      include:
      - master
    paths:
      include:
        - api/*

  pool:
    vmImage: "ubuntu-latest"
  
  variables:
    azureSubscription: azure

  stages:
    - stage: API-CI
      displayName: Backend API CI
      jobs:
        - job: Backend-API-CI
          displayName: Build Test and Publish
          steps:
          - task: UseDotNet@2
            displayName: Dotnet version 3.1.100
            inputs:
              version: '3.1.100'

          - task: DotNetCoreCLI@2
            displayName: Build
            inputs:
              command: build
              projects: '**/*.csproj'
              arguments: '--configuration Release'

          - task: DotNetCoreCLI@2
            displayName: Test
            inputs:
              command: test
              projects: '**/*Tests/*.csproj'
              arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'
  
          - task: DotNetCoreCLI@2
            displayName: Publish
            inputs:
              command: publish
              publishWebProjects: True
              arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
              zipAfterPublish: True
  
          - task: PublishBuildArtifacts@1
            displayName: Publish Artifacts
            inputs:
              pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
             
      - stage: Backend-API-CD
        displayName: Deploy App 
        jobs:
          - job: RegionalMaxtrixDeployment
            displayName: Deploy App to Regional App Service
            strategy:
              matrix:
                westus2:
                  region: westus2
                eastus:
                  region: eastus
                centralus:
                  region: centralus
              steps:         
                - task: AzureRMWebAppDeployment@4
                  displayName: Deploy
                  inputs:
                  ConnectionType: 'AzureRM'
                  azureSubscription: $(azureSubscription)
                  appType: 'apiApp'
                  WebAppName: 'backend-prodoh1-urlist-dev-$(region)'
                  packageForLinux: '$(Build.ArtifactStagingDirectory)/**/*.zip'
   
  
  
  
  
              
  
  
  
  
  
                
           
  
  