# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - master

pr: none

pool:
  vmImage: "ubuntu-latest"

jobs:
  - job: DeployInfrastructure
    displayName: Deploy Infrastructure
    strategy:
      matrix:
        westus2:
          region: westus2
        eastus:
          region: eastus
        centralus:
          region: centralus
    steps:
      - task: AzureCLI@2
        inputs:
          azureSubscription: "PELITTLE TEAM - CSE DWR(d36d0808-a967-4f73-9fdc-32ea232fc81d)"
          scriptType: "bash"
          scriptLocation: "scriptPath"
          scriptPath: "./deployment/arm/deploy-region.sh"
          arguments: "prodoh urlist dev $(region)"
