name: deploy-infrastructure

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - deployment/*
      - pipelines/deploy-infrastructure.yml

pr: none

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: Development
    displayName: Development
    variables:
      - group: prodoh-urlist-dev
    jobs:
    - template: templates/iac-deploy-environment.yml
      parameters:
        subscription: 'PELITTLE TEAM - CSE DWR(d36d0808-a967-4f73-9fdc-32ea232fc81d)'
        businessUnit: $(businessUnit)
        appName: $(appName)
        environment: dev
        regions:
          - westus2

  - stage: Staging
    displayName: Staging
    variables:
      - group: prodoh-urlist-staging
    jobs:
    - template: templates/iac-deploy-environment.yml
      parameters:
        subscription: 'PELITTLE TEAM - CSE DWR(d36d0808-a967-4f73-9fdc-32ea232fc81d)'
        businessUnit: $(businessUnit)
        appName: $(appName)
        environment: staging
        regions:
          - westus2
          - eastus

  - stage: Production
    displayName: Production
    variables:
      - group: prodoh-urlist-prod
    jobs:
    - template: templates/iac-deploy-environment.yml
      parameters:
        subscription: 'PELITTLE TEAM - CSE DWR(d36d0808-a967-4f73-9fdc-32ea232fc81d)'
        businessUnit: $(businessUnit)
        appName: $(appName)
        environment: prod
        regions:
          - westus2
          - eastus
          - centralus
