trigger:
  - master

pr: none

pool:
  vmImage: "ubuntu-latest"

variables:
  globalArguments: prodoh urlist dev westus2 eastus centralus
  azureSubscription: azure

stages:
  - stage: DeployCosmosDB
    displayName: Global
    jobs:
      - job: DeployCosmosDB
        displayName: Deploy Cosmos DB
        steps:
          - task: AzureCLI@2
            displayName: Deploy ARM Template
            inputs:
              azureSubscription: $(azureSubscription)
              scriptType: "bash"
              scriptLocation: "scriptPath"
              scriptPath: "./deployment/arm/deploy-cosmosdb.sh"
              arguments: $(globalArguments)
  - stage: DeployRegionalInfrastructure
    displayName: Regional
    jobs:
      - job: RegionalMaxtrixDeployment
        displayName: Resource Group
        strategy:
          matrix:
            westus2:
              region: westus2
            eastus:
              region: eastus
            centralus:
              region: centralus
        steps:
          - task: AzureCLI@2
            displayName: Deploy ARM Template
            inputs:
              azureSubscription: $(azureSubscription)
              scriptType: "bash"
              scriptLocation: "scriptPath"
              scriptPath: "./deployment/arm/deploy-region.sh"
              arguments: "prodoh urlist dev $(region)"
          - task: AzureAppServiceSettings@1
            displayName: Azure App Service Settings
            inputs:
              resourceGroupName: "rg-prodoh-urlist-dev-$(region)"
              azureSubscription: $(azureSubscription)
              appName: "backend-prodoh-urlist-dev-$(region)"
              appSettings: |
                [
                  {
                    "name": "CosmosSettings:AccountName",
                    "value": "tara",
                    "slotSetting": false
                  },
                  {
                    "name": "CosmosSettings:AuthKey",
                    "value":"tu", 
                    "slotSetting": false
                  }
                ]
                  