name: $(Date:yyyyMMdd)$(Rev:.r) # build numbering format

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - deployment/*
      - pipelines/deploy-infrastructure.yml
      - pipelines/templates/iac-deploy-environment.yml
      - pipelines/templates/deployment-gate.yml

pr: none

pool:
  vmImage: "ubuntu-latest"

variables:
  - group: prodoh-urlist-common

stages:
  - stage: Development
    displayName: Development
    variables:
      - group: prodoh-urlist-dev
    jobs:
    - template: templates/iac-deploy-environment.yml
      parameters:
        serviceConnection: $(serviceConnection)
        subscriptionId: $(subscriptionId)
        businessUnit: $(businessUnit)
        appName: $(appName)
        environment: dev
        regions:
          - westus2

  - stage: Staging
    displayName: Staging
    variables:
      - group: prodoh-urlist-staging
    jobs:
    - template: templates/iac-deploy-environment.yml
      parameters:
        serviceConnection: $(serviceConnection)
        subscriptionId: $(subscriptionId)
        businessUnit: $(businessUnit)
        appName: $(appName)
        environment: staging
        regions:
          - westus2
          - eastus

  - stage: Production
    displayName: Production
    variables:
      - group: prodoh-urlist-prod
    jobs:
    - template: templates/iac-deploy-environment.yml
      parameters:
        serviceConnection: $(serviceConnection)
        subscriptionId: $(subscriptionId)
        businessUnit: $(businessUnit)
        appName: $(appName)
        environment: prod
        regions:
          - westus2
          - eastus
          - centralus
