trigger:
  branches:
    include:
      - master
  paths:
    include:
      - deployment/*
      - pipelines/deploy-infrastructure.yml

pr: none

pool:
  vmImage: "ubuntu-latest"

variables:
  - group: prodoh-urlist-variable-group

stages:
  - stage: DeployRegionalInfrastructure
    displayName: Regional
    jobs:
      - job: RegionalMaxtrixDeployment
        displayName: Resource Group
        strategy:
          matrix:
            westus2:
              region: westus2
            eastus:
              region: eastus
            centralus:
              region: centralus
        steps:
          - task: AzureCLI@2
            displayName: Deploy ARM Template
            inputs:
              azureSubscription: $(azureSubscription)
              scriptType: "bash"
              scriptLocation: "scriptPath"
              scriptPath: "./deployment/arm/deploy-region.sh"
              arguments: "prodoh urlist dev $(region)"

  - stage: DeployGlobalInfrastructure
    displayName: Global
    jobs:
      - job: DeployGlobalInfrastructure
        displayName: Resources
        steps:
          - task: AzureCLI@2
            displayName: Deploy ARM Template
            inputs:
              azureSubscription: $(azureSubscription)
              scriptType: "bash"
              scriptLocation: "scriptPath"
              scriptPath: "./deployment/arm/deploy-global.sh"
              arguments: "prodoh urlist dev westus2 eastus centralus"