name: $(Date:yyyyMMdd)$(Rev:.r) # build numbering format

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - frontend/*
      - pipelines/frontend-build.yml
      - pipelines/frontend-deploy.yml
      - pipelines/templates/frontend-build.yml
      - pipelines/templates/frontend-deploy-environment.yml
      - pipelines/templates/deployment-gate.yml

pr: none

variables:
  - group: prodoh-urlist-common

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: Development
    displayName: Development
    variables:
      - group: prodoh-urlist-dev
    jobs:
      - template: templates/frontend-deploy-environment.yml
        parameters:
          subscription: $(azureSubscription)
          businessUnit: $(businessUnit)
          appName: $(appName)
          environment: dev
          regions:
            - westus2

  - stage: Staging
    displayName: Staging
    dependsOn: Development
    variables:
      - group: prodoh-urlist-staging
    jobs:
      - template: templates/frontend-deploy-environment.yml
        parameters:
          subscription: $(azureSubscription)
          businessUnit: $(businessUnit)
          appName: $(appName)
          environment: staging
          regions:
            - westus2
            - eastus

  - stage: Production
    displayName: Production
    dependsOn: Staging
    variables:
      - group: prodoh-urlist-prod
    jobs:
      - template: templates/frontend-deploy-environment.yml
        parameters:
          subscription: $(azureSubscription)
          businessUnit: $(businessUnit)
          appName: $(appName)
          environment: prod
          regions:
            - westus2
            - eastus
            - centralus
